version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - .build/data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: classique_password
      MYSQL_DATABASE: classique_db
      MYSQL_USER: classique
      MYSQL_PASSWORD: classique_password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: classique
      WORDPRESS_DB_PASSWORD: classique_password
      WORDPRESS_DB_NAME: classique_db
